# Xiaomi Air Purifier 2
- alias: Air Purifier mode change
  trigger:
    entity_id: input_select.xiaomi_airpurifier_mode
    platform: state
  action:
    service: fan.set_preset_mode
    data_template:
      entity_id: fan.xiaomi_air_purifier_2
      preset_mode: '{{ states.input_select.xiaomi_airpurifier_mode.state }}'
- alias: Air Purifier mode changed
  trigger:
    platform: state
    entity_id: fan.xiaomi_air_purifier_2
  condition:
    condition: not
    conditions:
      - condition: state
        entity_id: fan.xiaomi_air_purifier_2
        attribute: speed
        state: null
  action:
    service: input_select.select_option
    entity_id: input_select.xiaomi_airpurifier_mode
    data_template:
      option: '{{ states.fan.xiaomi_air_purifier_2.attributes.speed }}'
- alias: Air Purifier favorite level change
  trigger:
    entity_id: input_number.xiaomi_airpurifier_favorite_level
    platform: state
  action:
    service: xiaomi_miio.fan_set_favorite_level
    data_template:
      entity_id: fan.xiaomi_air_purifier_2
      level: '{{ states.input_number.xiaomi_airpurifier_favorite_level.state | int }}'
- alias: Air Purifier favorite level changed
  trigger:
    platform: state
    entity_id: fan.xiaomi_air_purifier_2
  action:
    service: input_number.set_value
    entity_id: input_number.xiaomi_airpurifier_favorite_level
    data_template:
      value: '{{ states.fan.xiaomi_air_purifier_2.attributes.favorite_level }}'

# Humidifier Bedroom
- alias: Select operation mode by input select
  trigger:
    entity_id: input_select.xiaomi_humidifier_bedroom_mode
    platform: state
  action:
    service: fan.set_speed
    data_template:
      entity_id: fan.xiaomi_humidifier_bedroom
      speed: '{{ states.input_select.xiaomi_humidifier_mode.state }}'
- alias: Humidifier mode changed
  trigger:
    platform: state
    entity_id: fan.xiaomi_humidifier_bedroom
  condition:
    condition: not
    conditions:
      - condition: state
        entity_id: fan.xiaomi_humidifier_bedroom
        attribute: speed
        state: none
  action:
    service: input_select.select_option
    entity_id: input_select.xiaomi_humidifier_bedroom_mode
    data_template:
      option: '{{ states.fan.xiaomi_humidifier_bedroom.attributes.speed }}'
- alias: Select target humidity
  trigger:
    platform: state
    entity_id: input_number.xiaomi_humidifier_bedroom_target_level
  action:
    service: xiaomi_miio.fan_set_target_humidity
    data_template:
      entity_id: fan.xiaomi_humidifier_bedroom
      humidity: '{{ states.input_number.xiaomi_humidifier_bedroom_target_level.state|int }}'
- alias: Monitor and update target humidity value
  trigger:
    platform: state
    entity_id: sensor.xiaomi_humidifier_bedroom_target_level
  action:
    service: input_number.set_value
    entity_id: input_number.xiaomi_humidifier_bedroom_target_level
    data_template:
      value: '{{ states.fan.xiaomi_humidifier_bedroom_target_level.attributes.target_humidity }}'
- alias: Turn off humidifier below specified water level # Not tested - check if works properly
  trigger:
    platform: numeric_state
    entity_id: sensor.xiaomi_humidifier_bedroom_depth
    below: 10
  condition:
    condition: template
    value_template: "{{ (trigger.to_state.state | int) != 0 }}"
  action:
    service: fan.turn_off
    data:
      entity_id: xiaomi_humidifier_bedroom

# Humidifier
- alias: Select operation mode by input select
  trigger:
    entity_id: input_select.xiaomi_humidifier_mode
    platform: state
  action:
    service: fan.set_speed
    data_template:
      entity_id: fan.xiaomi_humidifier
      speed: '{{ states.input_select.xiaomi_humidifier_mode.state }}'
- alias: Humidifier mode changed
  trigger:
    platform: state
    entity_id: fan.xiaomi_humidifier
  condition:
    condition: not
    conditions:
      - condition: state
        entity_id: fan.xiaomi_humidifier
        attribute: speed
        state: none
  action:
    service: input_select.select_option
    entity_id: input_select.xiaomi_humidifier_mode
    data_template:
      option: '{{ states.fan.xiaomi_humidifier.attributes.speed }}'
- alias: Select target humidity
  trigger:
    platform: state
    entity_id: input_number.xiaomi_humidifier_target_level
  action:
    service: xiaomi_miio.fan_set_target_humidity
    data_template:
      entity_id: fan.xiaomi_humidifier
      humidity: '{{ states.input_number.xiaomi_humidifier_target_level.state|int }}'
- alias: Monitor and update target humidity value
  trigger:
    platform: state
    entity_id: sensor.xiaomi_humidifier_target_level
  action:
    service: input_number.set_value
    entity_id: input_number.xiaomi_humidifier_target_level
    data_template:
      value: '{{ states.fan.xiaomi_humidifier_target_level.attributes.target_humidity }}'
- alias: Turn off humidifier below specified water level # Not tested - check if works properly
  trigger:
    platform: numeric_state
    entity_id: sensor.xiaomi_humidifier_depth
    below: 10
  condition:
    condition: template
    value_template: "{{ (trigger.to_state.state | int) != 0 }}"
  action:
    service: fan.turn_off
    data:
      entity_id: xiaomi_humidifier

