# Xiaomi Roborock Map Entity
- platform: xiaomi_cloud_map_extractor
  host: !secret xiaomi_vacuum_host
  token: !secret xiaomi_vacuum_token
  username: !secret mi_home_username
  password: !secret mi_home_password
  draw: ['all']
  attributes:
    - calibration_points 
