# Xiaomi Roborock Map Entity
- platform: xiaomi_cloud_map_extractor
  host: !secret xiaomi_vacuum_host
  token: !secret xiaomi_vacuum_token
  username: !secret mi_home_username
  password: !secret mi_home_password
  draw: ['all']
  colors:
    color_map_outside: [0, 0, 0]
  attributes:
    - calibration_points
  map_transformation:
    scale: 1
    trim:
      top: 20
      bottom: 15
      left: 25
      right: 25
  store_map_image: true
  store_map_path: /config/www

- platform: generic
  name: DaFang3
  username: !secret dafang_user
  password: !secret dafang_pass
  authentication: basic
  still_image_url: !secret dafang_image_url
  verify_ssl: false
  scan_interval: 2
