
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

switch: !include switch.yaml
sensor: !include sensor.yaml
camera: !include camera.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

sonoff:
  username: !secret so_username
  password: !secret so_password

remote:
  - platform: xiaomi_miio
    host: !secret xiaomi_remote_ir_host
    token: !secret xiaomi_remote_ir_token
    name: IR remote
    commands:
      fan_toggle:
        command:
          - raw:mMymMwlkznMwlgBCziYSyaTIAw5gAIczARKbAGsBGc0AiIAxACJAscAiQI/BZWbTkEhAbIBaYAyAGqBs8BVQXyAR8HXwbFAEKbTmbgosEbM0CR8A1Qh8BjsAjwCPDZ8EgwvvFG8AhgSPB+8U/wR6m05DHIFHxs/AaUOJgbPBj8BHw2fIXgL7wEZgAA==
      fan_speed:
        command:
          - raw:mMymkwlkznEwlkxmUzAIWaTIAwwBEAa8BpZgAR4BHyyYzGcga9N5vNQUMmICxABmBq4FiAImBHALPgEeARgNfg14Cg4LqAYoD6wGsgGICz4BHg1wFDU3m4MViUeGvgDXgEcAIQDXgfUGvoKHhMUA0or3jKQDF4H3ih+DX4FkgxLAAA==
      fan_time_mode:
        command:
          - raw:mMymcwlkznEwlgBETSZAGHMAEamMymICxABsA0gEcAWeBH4BDzebgjpNAa/AscGvwYvBr8Gvwa9moNfzOcgRtMQCCDy4BpwR4AjMGvwI/Br4UPwPtCmUNfwCOAEQCxgEYBr8GvxQ/ARKbA1uCWYNfhr+B9ANbh9uKH4XmACIA0sA
      fan_oscilation:
        command:
          - raw:mMymEwlk0mUwlgBETOcAGHNgEXmgDXzKZgEUA14BHgEPN5vOQLKAISZgIkCP4KHg1+FDwEfg1+F4kxm4BBTUEfwa/BHsDWACCARgGvwa/Br8Edga4Aa8WegofDg8GvwUPDX8Nfwj/FD8I/ga+BiIGvwR5gA=
      fan_breeze_mode:
        command:
          - raw:mMymEwlk0mUwlkxmQAhTOcgBlOADDmYAjTObAEGBGcxAaoCcwCFARcB4wJ0As8CxZvOAH3A6UCPwhqAxYGvwYqA14EewDDm83CzgFA5jNwCCmgGvgmQFVoOngESChAFmTebgGoF5AEfgNcDX4a9CG+BZ4NZidQCh4a/B5aIaQOnga+KH4obgGmGv4a+QAA==
      mibox_toggle:
        command:
          - raw:mMwmswlk1mkwlk2mYA8zGaTIAjgGfAQ8BDwCLmEA
      lg_tv_toggle:
        command:
          - raw:nMwmMwlk0mk1mEsms0AD+YSyYzacgOlOAGOmYB+zaZARlNgB1mIBiAYFMZsCV4JTgMqBeQEUAEeAH4M0gvQAx4P7gDoGiQQ/gt+Dr4BHgENMIAA=

# vacuum rooms
# 2 Bedroom
# 3 Children room
# 1 Bathtoom
# 16 Hall
# 21 Kitchen
# 17 window
# 19 carpet
# 18 bar
input_boolean:
  bedroom_clean:
    name: Bedroom
  hall_clean:
    name: Hall
  children_room_clean:
    name: Children room
  bath_room_clean:
    name: Bathroom
  kitchen_clean:
    name: Kitchen
  bar_clean:
    name: Bar
  carpet_clean:
    name: Carpet
  table_clean:
    name: Table

input_select:
  xiaomi_airpurifier_mode:
    name: Mode
    options:
      - Auto
      - Silent
      - Favorite
    icon: "mdi:animation-outline"
  xiaomi_humidifier_mode:
    name: Mode
    options:
     - Silent
     - Medium
     - High
     - Auto
    icon: "mdi:animation-outline"
  xiaomi_humidifier_bedroom_mode:
    name: Mode
    options:
     - Silent
     - Medium
     - High
     - Auto
    icon: "mdi:animation-outline"

input_number:
  xiaomi_humidifier_bedroom_target_level:
    name: Set target humidity
    min: 30
    max: 80
    step: 10
    icon: "mdi:weather-windy"
  xiaomi_humidifier_target_level:
    name: Set target humidity
    min: 40
    max: 80
    step: 10
    icon: "mdi:weather-windy"

influxdb:
  username: !secret influxdb_user
  password: !secret influxdb_pass
  max_retries: 3
  default_measurement: state
  include:
    entities:
      - sensor.temp_balcony_temperature
      - sensor.temp_balcony_humidity
      - sensor.temp_balcony_pressure

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret chat_id

notify:
  - platform: telegram
    name: telegram
    chat_id: !secret chat_id

media_player:
  - platform: yamaha
    host: !secret yamaha_receiver_host
    name: "Yamaha"
    zone_names:
      Main_Zone: "Salon"
  - platform: androidtv
    host: !secret mibox_host
    name: MiBOX3
