
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

switch: !include switch.yaml
sensor: !include sensor.yaml
camera: !include camera.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

sonoff:
  username: !secret so_username
  password: !secret so_password

input_select:
  xiaomi_airpurifier_mode:
    name: Mode
    options:
      - Auto
      - Silent
      - Favorite
    icon: "mdi:animation-outline"
  xiaomi_humidifier_mode:
    name: Mode
    options:
     - Silent
     - Medium
     - High
     - Auto
    icon: "mdi:animation-outline"
  xiaomi_humidifier_bedroom_mode:
    name: Mode
    options:
     - Silent
     - Medium
     - High
     - Auto
    icon: "mdi:animation-outline"

input_number:
  xiaomi_airpurifier_favorite_level:
    name: "Favorite level"
    initial: 0
    min: 0
    max: 14
    step: 1
    icon: "mdi:weather-windy"
  xiaomi_humidifier_bedroom_target_level:
    name: Set target humidity
    min: 30
    max: 80
    step: 10
    icon: "mdi:weather-windy"
  xiaomi_humidifier_target_level:
    name: Set target humidity
    min: 30
    max: 80
    step: 10
    icon: "mdi:weather-windy"

influxdb:
  username: !secret influxdb_user
  password: !secret influxdb_pass
  max_retries: 3
  default_measurement: state
  include:
    entities:
      - sensor.0x00158d00022ca75c_temperature
      - sensor.0x00158d00022ca75c_humidity
      - sensor.0x00158d00022ca75c_pressure