- platform: template
  sensors: 

    # Air Purifier
    xiaomi_airpurifier_aqi:
      friendly_name: "Air Purifier"
      unit_of_measurement: 'AQI'
      value_template: "{{ state_attr('fan.xiaomi_air_purifier_2', 'aqi') }}"
    xiaomi_airpurifier_humidity:
      friendly_name: "Air Purifier humidity"
      unit_of_measurement: '%'
      value_template: "{{ state_attr('fan.xiaomi_air_purifier_2', 'humidity') }}"
    xiaomi_airpurifier_temperature:
      friendly_name: "Air Purifier temperature"
      unit_of_measurement: '째C'
      value_template: "{{ state_attr('fan.xiaomi_air_purifier_2', 'temperature') }}"
    xiaomi_airpurifier_speed:
      friendly_name: "Fan speed"
      value_template: "{{ state_attr('fan.xiaomi_air_purifier_2', 'motor_speed') }}"
      unit_of_measurement: "rpm"
      icon_template: "mdi:speedometer"
    xiaomi_airpurifier_filter_remaining:
      friendly_name: "Filter remaining"
      value_template: "{{ state_attr('fan.xiaomi_air_purifier_2', 'filter_life_remaining') }}"
      unit_of_measurement: "%"
      icon_template: "mdi:heart-outline"

    # Humifidier Bedroom
    xiaomi_humidifier_bedroom_humidity:
      friendly_name: "Humidifier Humidity"
      unit_of_measurement: '%'
      value_template: "{{ state_attr('fan.xiaomi_humidifier_bedroom', 'humidity') }}"
    xiaomi_humidifier_bedroom_temperature:
      friendly_name: "Humidifier Temperature"
      unit_of_measurement: '째C'
      value_template: "{{ state_attr('fan.xiaomi_humidifier_bedroom', 'temperature') }}"
    xiaomi_humidifier_bedroom_depth:
      friendly_name: "Humidifier water level"
      unit_of_measurement: '%'
      value_template: "{{ state_attr('fan.xiaomi_humidifier_bedroom', 'depth') }}"
      icon_template: "mdi:water-outline"
    xiaomi_humidifier_bedroom_target_level:
      friendly_name: "Humidifier target Level"
      unit_of_measurement: '%'
      value_template: "{{ state_attr('fan.xiaomi_humidifier_bedroom', 'target_level') }}"
    xiaomi_humidifier_bedroom_target_level:
      friendly_name: "Humidifier fan speed"
      unit_of_measurement: 'rpm'
      value_template: "{{ state_attr('fan.xiaomi_humidifier_bedroom', 'motor_speed') }}"
      icon_template: "mdi:speedometer"
    
    # Humidifier
    xiaomi_humidifier_humidity:
      friendly_name: "Humidifier Humidity"
      unit_of_measurement: '%'
      value_template: "{{ state_attr('fan.xiaomi_humidifier', 'humidity') }}"
    xiaomi_humidifier_temperature:
      friendly_name: "Humidifier Temperature"
      unit_of_measurement: '째C'
      value_template: "{{ state_attr('fan.xiaomi_humidifier', 'temperature') }}"
    xiaomi_humidifier_depth:
      friendly_name: "Humidifier water level"
      unit_of_measurement: '%'
      value_template: "{{ state_attr('fan.xiaomi_humidifier', 'depth') }}"
      icon_template: "mdi:water-outline"
    xiaomi_humidifier_target_level:
      friendly_name: "Humidifier target Level"
      unit_of_measurement: '%'
      value_template: "{{ state_attr('fan.xiaomi_humidifier', 'target_level') }}"
    xiaomi_humidifier_target_level:
      friendly_name: "Humidifier fan speed"
      unit_of_measurement: 'rpm'
      value_template: "{{ state_attr('fan.xiaomi_humidifier', 'motor_speed') }}"
      icon_template: "mdi:speedometer"

- platform: time_date
  display_options: 
   - 'time'
   - 'date'
   - 'date_time'

# Kids room average humidity
- platform: min_max
  name: kids_room_average_temperature
  type: mean
  entity_ids:
    - sensor.xiaomi_airpurifier_temperature
    - sensor.xiaomi_humidifier_temperature
    - sensor.temp_kids_room_temperature

# Kids room average humidity
- platform: min_max
  name: kids_room_average_humidity
  type: mean
  entity_ids:
    - sensor.xiaomi_airpurifier_humidity
    - sensor.xiaomi_humidifier_humidity
    - sensor.temp_kids_room_humidity

# Bedroom average temperature
- platform: min_max
  name: bedroom_average_temperature
  type: mean
  entity_ids:
    - sensor.xiaomi_humidifier_bedroom_temperature


# Bedroom average humidity
- platform: min_max
  name: bedroom_average_humidity
  type: mean
  entity_ids:
    - sensor.xiaomi_humidifier_bedroom_humidity

# Hall average temperature
- platform: min_max
  name: hall_average_temperature
  type: mean
  entity_ids:
    - sensor.hall_motion_sensor_temperature

# Raspberry Pi
# The systemmonitor sensor platform allows you to monitor disk usage, memory usage, CPU usage, and running processes.
# https://www.home-assistant.io/integrations/systemmonitor/
- platform: systemmonitor
  resources:
    - type: processor_use
    - type: load_1m 
    - type: load_5m
    - type: load_15m
    - type: memory_use
    - type: memory_use_percent
    - type: swap_use
    - type: swap_use_percent
    - type: disk_use
    - type: disk_use_percent
    - type: last_boot

- platform: command_line
  name: CPU temperature
  command: "/bin/cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: '째C'
  value_template: '{{ (value | int /1000) | round(1) }}'


# Xiaomi BLE Temperature & Humidity Sensor 
# Disabled due to low link quality
# - platform: mitemp_bt
#   mac: "4C:65:A8:D8:AD:3F"
#   name: Bedroom Temp & Humidity BLE
#   force_update: true
#   monitored_conditions:
#     - temperature
#     - humidity
#     - battery