- platform: template
  switches:
    # Air Purifier
    xiaomi_airpurifier_led:
      friendly_name: "Air Purifier LED"
      value_template: "{{ is_state_attr('fan.xiaomi_air_purifier_2', 'led', true) }}"
      turn_on:
        service: xiaomi_miio.fan_set_led_on
        data:
          entity_id: fan.xiaomi_air_purifier_2
      turn_off:
        service: xiaomi_miio.fan_set_led_off
        data:
          entity_id: fan.xiaomi_air_purifier_2
      icon_template: "mdi:lightbulb-outline"
    xiaomi_airpurifier_child_lock:
      friendly_name: "Air Purifier child lock"
      value_template: "{{ is_state_attr('fan.xiaomi_air_purifier_2', 'child_lock', true) }}"
      turn_on:
        service: xiaomi_miio.fan_set_child_lock_on
        data:
          entity_id: fan.xiaomi_air_purifier_2
      turn_off:
        service: xiaomi_miio.fan_set_child_lock_off
        data:
          entity_id: fan.xiaomi_air_purifier_2
      icon_template: "mdi:lock-outline"
    xiaomi_airpurifier_buzzer:
      friendly_name: "Buzzer"
      value_template: "{{ is_state_attr('fan.xiaomi_air_purifier_2', 'buzzer', true) }}"
      turn_on:
        service: xiaomi_miio.fan_set_buzzer_on
        data:
          entity_id: fan.xiaomi_air_purifier_2
      turn_off:
        service: xiaomi_miio.fan_set_buzzer_off
        data:
          entity_id: fan.xiaomi_air_purifier_2
      icon_template: "mdi:volume-high"

    # Humidifier Bedroom
    xiaomi_humidifier_bedroom_led:
      friendly_name: "Humidifier LED"
      value_template: "{{ is_state_attr('fan.xiaomi_humidifier_bedroom', 'led_brightness', true) }}"
      turn_on:
        service: xiaomi_miio.fan_set_led_brightness
        data:
          entity_id: fan.xiaomi_humidifier_bedroom
          brightness: 1
      turn_off:
        service: xiaomi_miio.fan_set_led_brightness
        data:
          entity_id: fan.xiaomi_humidifier_bedroom
          brightness: 2
      icon_template: "mdi:lightbulb-outline"
    xiaomi_humidifier_bedroom_child_lock:
      friendly_name: "Humidifier child lock"
      value_template: "{{ is_state_attr('fan.xiaomi_humidifier_bedroom', 'child_lock', true) }}"
      turn_on:
        service: xiaomi_miio.fan_set_child_lock_on
        data:
          entity_id: fan.xiaomi_humidifier_bedroom
      turn_off:
        service: xiaomi_miio.fan_set_child_lock_off
        data:
          entity_id: fan.xiaomi_humidifier_bedroom
      icon_template: "mdi:lock-outline"
    xiaomi_humidifier_bedroom_dry_mode:
      friendly_name: "Dry mode"
      value_template: "{{ is_state_attr('fan.xiaomi_humidifier_bedroom', 'dry', true) }}"
      turn_on:
        service: xiaomi_miio.fan_set_dry_on
        data:
          entity_id: fan.xiaomi_humidifier_bedroom
      turn_off:
        service: xiaomi_miio.fan_set_dry_off
        data:
          entity_id: fan.xiaomi_humidifier_bedroom
      icon_template: "mdi:water-off-outline"

    # Humidifier
    xiaomi_humidifier_led:
      friendly_name: "Humidifier LED"
      value_template: "{{ is_state_attr('fan.xiaomi_humidifier', 'led_brightness', true) }}"
      turn_on:
        service: xiaomi_miio.fan_set_led_brightness
        data:
          entity_id: fan.xiaomi_humidifier
          brightness: 1
      turn_off:
        service: xiaomi_miio.fan_set_led_brightness
        data:
          entity_id: fan.xiaomi_humidifier
          brightness: 2
      icon_template: "mdi:lightbulb-outline"
    xiaomi_humidifier_child_lock:
      friendly_name: "Humidifier child lock"
      value_template: "{{ is_state_attr('fan.xiaomi_humidifier', 'child_lock', true) }}"
      turn_on:
        service: xiaomi_miio.fan_set_child_lock_on
        data:
          entity_id: fan.xiaomi_humidifier
      turn_off:
        service: xiaomi_miio.fan_set_child_lock_off
        data:
          entity_id: fan.xiaomi_humidifier
      icon_template: "mdi:lock-outline"
    xiaomi_humidifier_dry_mode:
      friendly_name: "Dry mode"
      value_template: "{{ is_state_attr('fan.xiaomi_humidifier', 'dry', true) }}"
      turn_on:
        service: xiaomi_miio.fan_set_dry_on
        data:
          entity_id: fan.xiaomi_humidifier
      turn_off:
        service: xiaomi_miio.fan_set_dry_off
        data:
          entity_id: fan.xiaomi_humidifier
      icon_template: "mdi:water-off-outline"